#!/usr/bin/env python3
"""
save_waypoint.py

เครื่องมือบันทึก Navigation Waypoints จากตำแหน่งปัจจุบันของ robot
รองรับทั้ง teleop (ใช้ /amr_mtt/odom) และ Nav2 (ใช้ /amcl_pose)

Usage:
  ros2 run amr_mtt_task_planner save_waypoint

วิธีใช้:
  1. Launch simulation (ros2_nvidia launch amr_mtt_moveit_config moveit.launch.py)
  2. ขับ robot ด้วย teleop ไปตำแหน่งที่ต้องการ
  3. รัน: ros2 run amr_mtt_task_planner save_waypoint
  4. พิมพ์ชื่อ waypoint แล้วกด Enter → พิกัดถูกบันทึกทันที
  5. พิมพ์ "done" เพื่อจบและดูสรุป
"""

import math
import rclpy
from rclpy.node import Node
from nav_msgs.msg import Odometry
from geometry_msgs.msg import PoseWithCovarianceStamped

SAVE_FILE = '/tmp/nav_waypoints.py'

# Topic names (ตาม launch file ของโปรเจคนี้)
ODOM_TOPIC  = '/amr_mtt/odom'   # diff_drive_controller remapped
AMCL_TOPIC  = '/amcl_pose'      # Nav2 (ใช้ถ้ามี)


def quaternion_to_yaw_deg(qx, qy, qz, qw) -> float:
    siny_cosp = 2.0 * (qw * qz + qx * qy)
    cosy_cosp = 1.0 - 2.0 * (qy * qy + qz * qz)
    return math.degrees(math.atan2(siny_cosp, cosy_cosp))


class WaypointSaverNode(Node):
    def __init__(self):
        super().__init__('waypoint_saver_node')
        self.current_pose = None
        self.pose_source = None
        self.saved_waypoints = []

        # /amr_mtt/odom (ใช้ได้เสมอขณะ simulation รัน)
        self.odom_sub = self.create_subscription(
            Odometry, ODOM_TOPIC, self._odom_callback, 10
        )

        # /amcl_pose (เฉพาะขณะรัน Nav2)
        self.amcl_sub = self.create_subscription(
            PoseWithCovarianceStamped, AMCL_TOPIC, self._amcl_callback, 10
        )

        self.get_logger().info(f'Subscribed to {ODOM_TOPIC} and {AMCL_TOPIC}')

    def _odom_callback(self, msg: Odometry):
        if self.pose_source != 'amcl_pose':
            self.current_pose = msg.pose.pose
            self.pose_source = 'odom'

    def _amcl_callback(self, msg: PoseWithCovarianceStamped):
        self.current_pose = msg.pose.pose
        self.pose_source = 'amcl_pose'

    def refresh_pose(self):
        """spin สั้นๆ เพื่อรับ pose ล่าสุด"""
        for _ in range(20):
            rclpy.spin_once(self, timeout_sec=0.05)

    def save_current(self, name: str):
        self.refresh_pose()
        if self.current_pose is None:
            print(f'  [ERROR] ไม่ได้รับ pose จาก {ODOM_TOPIC} กรุณาตรวจสอบว่า simulation กำลังรันอยู่')
            return

        x   = self.current_pose.position.x
        y   = self.current_pose.position.y
        q   = self.current_pose.orientation
        yaw = quaternion_to_yaw_deg(q.x, q.y, q.z, q.w)

        self.saved_waypoints.append((name, x, y, yaw))
        print(f'\n  ✅ บันทึกแล้ว [{self.pose_source}]')
        print(f'     {name}: x={x:.4f}, y={y:.4f}, yaw={yaw:.1f}°')
        print(f'     → ("{name}", {x:.4f}, {y:.4f}, {yaw:.1f}),\n')

    def print_summary(self):
        if not self.saved_waypoints:
            print('\n  [ไม่มี waypoint ที่บันทึก]')
            return

        print('\n' + '='*60)
        print('  📋 NAV_WAYPOINTS — copy ไปใส่ใน nav_sequence.py')
        print('='*60)
        print('NAV_WAYPOINTS = [')
        for name, x, y, yaw in self.saved_waypoints:
            print(f'    ("{name}", {x:.4f}, {y:.4f}, {yaw:.1f}),')
        print(']')
        print('='*60)

        with open(SAVE_FILE, 'w') as f:
            f.write('# Auto-generated by save_waypoint.py\n')
            f.write('NAV_WAYPOINTS = [\n')
            for name, x, y, yaw in self.saved_waypoints:
                f.write(f'    ("{name}", {x:.4f}, {y:.4f}, {yaw:.1f}),\n')
            f.write(']\n')
        print(f'\n  💾 บันทึกลงไฟล์: {SAVE_FILE}')
        print('  📌 อ่านกลับ: cat /tmp/nav_waypoints.py')


def main(args=None):
    rclpy.init(args=args)
    node = WaypointSaverNode()

    print('\n' + '='*60)
    print('  🗺️  AMR MTT — Waypoint Saver')
    print(f'  Topic: {ODOM_TOPIC}')
    print('='*60)
    print('  รอรับ pose...')

    # รอรับ pose แรก (timeout 8 วินาที)
    timeout = 8.0
    elapsed = 0.0
    while rclpy.ok() and node.current_pose is None and elapsed < timeout:
        rclpy.spin_once(node, timeout_sec=0.2)
        elapsed += 0.2

    if node.current_pose is None:
        print(f'\n  [WARN] ไม่ได้รับ pose ใน {timeout:.0f}s')
        print(f'  ตรวจสอบว่า simulation รัน และ topic "{ODOM_TOPIC}" มีอยู่')
        print('  ลองรัน: ros2 topic echo /amr_mtt/odom --once\n')
    else:
        print(f'  ✅ Pose source: {node.pose_source}')
        p = node.current_pose
        yaw = quaternion_to_yaw_deg(p.orientation.x, p.orientation.y,
                                     p.orientation.z, p.orientation.w)
        print(f'  ตำแหน่งปัจจุบัน: x={p.position.x:.3f}, y={p.position.y:.3f}, yaw={yaw:.1f}°')

    print('\n  ขับ robot ไปตำแหน่งที่ต้องการ แล้วพิมพ์ชื่อ + Enter')
    print('  พิมพ์ "done" เพื่อจบ')
    print('='*60 + '\n')

    try:
        while rclpy.ok():
            rclpy.spin_once(node, timeout_sec=0.1)
            try:
                name = input('ชื่อ waypoint: ').strip()
            except EOFError:
                break

            if not name or name.lower() in ('done', 'q', 'exit'):
                break

            node.save_current(name)

    except KeyboardInterrupt:
        pass
    finally:
        node.print_summary()
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
