<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="amr_mtt">

    <!--................................ XACRO CONSTANTS .............................. -->

    <!-- หุ่นยนต์หนัก 60 kg -->
    <xacro:property name="chassis_mass" value="135"/>

    <xacro:property name="chassis_length" value="0.9"/>
    
    <xacro:property name="chassis_width" value="0.64"/>
    
    <xacro:property name="chassis_height" value="0.2"/>

    <!-- traction_wheel_mass (มวลของล้อขับเคลื่อน) -->
    <xacro:property name="traction_wheel_mass" value="4.6"/>

    <xacro:property name="traction_wheel_base" value="0.88"/>
    <xacro:property name="traction_max_wheel_torque" value="11.4"/>
    <xacro:property name="traction_wheel_friction" value="3.0"/>

    <xacro:property name="trolley_wheel_mass" value="0.1"/>
    <xacro:property name="trolley_track_width" value="0.5"/>
    <xacro:property name="trolley_wheel_friction" value="0.0"/>
    <xacro:property name="trolley_wheel_radius" value="0.06"/>
    <!-- a small constant -->
    <xacro:property name="eps" value="0.002"/>

    
    <!-- การระบุพารามิเตอร์ "รัศมีล้อ" (Wheel Radius) ระบุเส้นผ่านศูนย์กลางภายนอกสุดที่ 160 mm  
    ค่าที่ต้องใช้จริง: รัศมี = 160 mm / 2 = 80 mm = 0.08 m   -->
    <xacro:property name="traction_wheel_radius" value="0.08"/>
    
    <!--การระบุพารามิเตอร์ "ความกว้างล้อ" (Wheel Width) แบบระบุความกว้างรวมของล้อที่ 160 mm -->
    <xacro:property name="traction_wheel_width" value="0.06"/>

    <!-- พารามิเตอร์นี้คือระยะห่างระหว่าง "กึ่งกลางล้อซ้าย" ถึง "กึ่งกลางล้อขวา" -->
    <xacro:property name="traction_track_width" value="0.436"/>
    
    <xacro:property name="two_d_lidar_update_rate" value="30"/>
    <xacro:property name="two_d_lidar_sample_size" value="361"/>
    <xacro:property name="two_d_lidar_min_angle" value="0"/>
    <xacro:property name="two_d_lidar_max_angle" value="360"/>
    <xacro:property name="two_d_lidar_min_range" value="0.55"/>
    <xacro:property name="two_d_lidar_max_range" value="16"/>

    <xacro:property name="camera_baseline" value="0.06"/>
    <xacro:property name="camera_height" value="0.10"/>
    <xacro:property name="camera_horizontal_fov" value="60"/>

    <xacro:arg name="robot_namespace" default=""/>
    <xacro:arg name="wheel_odom_topic" default="odom" />
    <xacro:arg name="camera_enabled" default="false" />
    <xacro:arg name="stereo_camera_enabled" default="false" />
    <xacro:arg name="two_d_lidar_enabled" default="false" />
    <xacro:arg name="publish_wheel_odom_tf" default="true" />
    <xacro:arg name="conveyor_enabled" default="false"/>
    <xacro:arg name="ground_truth_frame" default="map"/>
    <xacro:arg name="sim_gazebo" default="false" />
    <xacro:arg name="sim_ign" default="false" />
    <xacro:arg name="sim_gz" default="false" />
    <xacro:arg name="odometry_source" default="world" />

    <xacro:property name="odometry_source" value="$(arg odometry_source)"/>

    <!-- UR5 Robot -->
    <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro"/>
    <xacro:arg name="ur_type" default="ur5"/>
    <xacro:arg name="joint_limit_params" default="$(find ur_description)/config/ur5/joint_limits.yaml"/>
    <xacro:arg name="kinematics_params" default="$(find ur_description)/config/ur5/default_kinematics.yaml"/>
    <xacro:arg name="physical_params" default="$(find ur_description)/config/ur5/physical_parameters.yaml"/>
    <xacro:arg name="visual_params" default="$(find ur_description)/config/ur5/visual_parameters.yaml"/>
    
    <!-- <xacro:arg name="initial_positions_file" default="$(find ur_description)/config/ur5/initial_positions.yaml"/> -->
    <xacro:arg name="initial_positions_file" default="$(find amr_mtt)/config/initial_positions.yaml"/>
    <xacro:property name="initial_positions_file" value="$(arg initial_positions_file)"/>

    <!--Gripper-->
    <!-- <xacro:include filename="$(find robotiq_description)/urdf/robotiq_2f_85_macro.urdf.xacro" /> -->

    <!-- ............................... LOAD MACROS ................................. -->

    <xacro:include filename="$(find amr_mtt)/urdf/materials.xacro"/>
    <xacro:include filename="$(find amr_mtt)/urdf/macros.xacro"/>

    <!-- <xacro:if value="$(arg sim_gazebo)">
        <xacro:include filename="$(find amr_mtt)/urdf/gazebo.xacro"/>
    </xacro:if> -->

    <xacro:if value="$(arg sim_ign)">
        <xacro:include filename="$(find amr_mtt)/urdf/ign.xacro"/>
    </xacro:if>

    <!-- <xacro:if value="$(arg sim_gz)">
        <xacro:include filename="$(find amr_mtt)/urdf/gz.xacro"/>
    </xacro:if> -->

    <!-- ................................ BASE LINK .................................. -->
    <link name="base_footprint"/>

    <link name="base_link"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0 ${chassis_height/2 + traction_wheel_radius}" rpy="0 0 0.0" />
    </joint>

    <link name="chassis_link">

        <collision>
            <origin xyz="0 0 -0.05" rpy="0 0 0" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <!-- <mesh filename="file://$(find amr_mtt)/meshes/amr_mtt_model/base_link.STL" scale="1 1 1"/> -->
                <mesh filename="package://amr_mtt/meshes/amr_mtt_model/base_link.STL" scale="1 1 1"/>
                
            </geometry>
            <material name="orange"/>
        </visual>

       <inertial>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <mass value="${chassis_mass}" />
            <inertia ixx="5.058" ixy="0" ixz="0"
                     iyy="9.562" iyz="0"
                     izz="13.720" />
        </inertial>

    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0.0 0 0" rpy="0 0 0.0" />
    </joint>


    <!-- ................................ UR5 ROBOT ARM .......................... -->
    <xacro:ur_robot
        name="ur5_arm"
        tf_prefix="ur5_"
        parent="base_link"
        
        joint_limits_parameters_file="$(arg joint_limit_params)"
        kinematics_parameters_file="$(arg kinematics_params)"
        physical_parameters_file="$(arg physical_params)"
        visual_parameters_file="$(arg visual_params)"

        use_fake_hardware="false"
        sim_ignition="true"
        initial_positions="${xacro.load_yaml(initial_positions_file)}"
    >
        <origin xyz="0.2 0 0.8" rpy="0 0 0"/> 
    </xacro:ur_robot>

    <!-- ................................ ROBOTIQ GRIPPER .......................... -->
    <!-- <xacro:robotiq_gripper 
        name="robotiq_gripper" 
        prefix="" 
        parent="ur5_tool0" 
        include_ros2_control="false">  <origin xyz="0 0 0" rpy="0 0 0"/> 
    </xacro:robotiq_gripper> -->

    <!-- ................................ WHEELS ..................................... -->

    <xacro:trolley_wheel cardinality="front" dexterity="left" origin_x="${chassis_length/2-0.10}" origin_y="${trolley_track_width/2}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>
    <xacro:trolley_wheel cardinality="front" dexterity="right" origin_x="${chassis_length/2-0.10}" origin_y="-${trolley_track_width/2}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>

    <xacro:trolley_wheel cardinality="back" dexterity="left" origin_x="-${chassis_length/2-0.10}" origin_y="${trolley_track_width/2}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>
    <xacro:trolley_wheel cardinality="back" dexterity="right" origin_x="-${chassis_length/2-0.10}" origin_y="-${trolley_track_width/2}" origin_z="-${trolley_wheel_radius+chassis_height/2}"/>

    <xacro:traction_wheel cardinality="middle" dexterity="left" origin_x="0" origin_y="${traction_track_width/2}" origin_z="-${chassis_height/2+2*trolley_wheel_radius+eps-traction_wheel_radius}"/>
    <xacro:traction_wheel cardinality="middle" dexterity="right" origin_x="0" origin_y="-${traction_track_width/2}" origin_z="-${chassis_height/2+2*trolley_wheel_radius+eps-traction_wheel_radius}"/>

    <!-- ............................. 2D LIDAR ........................................ -->

    <!-- ========================================================= -->
    <!-- .......................... FRONT LIDAR .................... -->
    <!-- ========================================================= -->
    <xacro:if value="$(arg two_d_lidar_enabled)">
        <link name="L_F_Lidar_Link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                   <mesh filename="package://amr_mtt/meshes/amr_mtt_model/L_F_Lidar_Link.STL" scale="1 1 1"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://amr_mtt/meshes/amr_mtt_model/L_F_Lidar_Link.STL" scale="1 1 1"/>
                    
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1" />
                </material>

            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.1"/>
                <xacro:cylinder_inertia m="0.1" r="0.075" h="0.06"/>
            </inertial>
        </link>

        <joint name="L_F_Lidar_joint" type="fixed">
            <parent link="base_link"/>
            <child link="L_F_Lidar_Link"/>
            <origin xyz="0.33905 0.18905 0.18259" rpy="3.1416 0 0.7854"/>
        </joint>

        <gazebo reference="L_F_Lidar_Link">
            <material>Gazebo/White</material>
        </gazebo>
    </xacro:if>

    <!-- ========================================================= -->
    <!-- .......................... REAR LIDAR .................... -->
    <!-- ========================================================= -->
    <xacro:if value="$(arg two_d_lidar_enabled)">
        <link name="R_B_Lidar_Link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://amr_mtt/meshes/amr_mtt_model/R_B_Lidar_Link.STL" scale="1 1 1"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://amr_mtt/meshes/amr_mtt_model/R_B_Lidar_Link.STL" scale="1 1 1"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1" />
                </material>

            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.1"/>
                <xacro:cylinder_inertia m="0.1" r="0.075" h="0.06"/>
            </inertial>
        </link>

        <joint name="R_B_Lidar_joint" type="fixed">
            <parent link="base_link"/>
            <child link="R_B_Lidar_Link"/>
            <!-- จุดติดตั้งด้านหลัง -->
            <origin xyz="-0.33905 -0.18905 0.18259" rpy="-3.1416 0 -0.7854"/>
        </joint>

        <gazebo reference="R_B_Lidar_Link">
            <material>Gazebo/White</material>
        </gazebo>
    </xacro:if>

    <!-- ............................. IMU ........................................ -->

    <link name="imu_frame"/>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_frame"/>
        <origin xyz="0.0 0.0 0.08" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- ............................. CAMERA ........................................ -->

    <xacro:if value="$(arg camera_enabled)">

        <!-- KINECT CAMERA -->

        <link name="kinect_camera">

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://amr_mtt/meshes/amr_mtt_model/F_Cam_Link.STL" scale="1 1 1"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://amr_mtt/meshes/amr_mtt_model/F_Cam_Link.STL" scale="1 1 1"/>
                </geometry>
                <material name="blue">
                    <color rgba="0 0 1 1" />
                </material>
            </visual>

            <inertial>
                <mass value="0.01"/>
                <xacro:box_inertia m="0.01" x="0.07" y="0.3" z = "0.09"/>
            </inertial>

        </link>

        <joint name="kinect_camera_joint" type="fixed">
            <origin rpy="0 0 0" xyz="${chassis_length/2} 0 0.26"/>
            <parent link="base_link"/>
            <child link="kinect_camera"/>
        </joint>

        <link name="kinect_camera_optical"/>

        <joint name="kinect_camera_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
            <parent link="kinect_camera"/>
            <child link="kinect_camera_optical"/>
        </joint>

    </xacro:if>

    <!-- .............................STEREO CAMERA ........................................ -->

    <xacro:if value="$(arg stereo_camera_enabled)">

        <!-- STEREO CAMERA -->

        <link name="stereo_camera">

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://amr_mtt/meshes/amr_mtt_model/F_Cam_Link.STL" scale="1 1 1"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://amr_mtt/meshes/amr_mtt_model/F_Cam_Link.STL" scale="1 1 1"/>
                </geometry>
                <material name="red">
                    <color rgba="1 0 0 1" />
                </material>

            </visual>

            <inertial>
                <mass value="0.01"/>
                <xacro:box_inertia m="0.01" x="0.07" y="0.3" z = "0.09"/>
            </inertial>

        </link>

        <joint name="stereo_camera_joint" type="fixed">
            <origin rpy="0 0 0" xyz="${chassis_length/2} 0 0.26"/>
            <parent link="base_link"/>
            <child link="stereo_camera"/>
        </joint>

        <link name="stereo_camera_optical"/>

        <joint name="stereo_camera_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
            <parent link="stereo_camera"/>
            <child link="stereo_camera_optical"/>
        </joint>

    </xacro:if>
</robot>