<?xml version="1.0"?>
<package format="3">
  <name>amr_mtt_docking</name>
  <version>1.0.0</version>
  <description>Enhanced Auto-Docking System for AMR-MTT</description>
  
  <maintainer email="s6703016411302@email.kmutnb.ac.th">Phuwaset Sibta</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Core ROS 2 -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rclcpp</exec_depend>

  <!-- Messages -->
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>

  <!-- TF -->
  <exec_depend>tf2_ros</exec_depend>

  <!-- Vision -->
  <exec_depend>cv_bridge</exec_depend>

  <!-- Base robot -->
  <exec_depend>amr_mtt_bot</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
